name: Deploy Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.17.0' 
          
      - name: Verify Node.js Version
        run: node -v

      - name: Deploy to VPS
        env:
          HOST: ${{ secrets.HOST_IP}} 
          USER: ${{ secrets.HOST_USER}} 
          PORT: ${{ secrets.PORT}}
          PRIVATE_KEY: ${{secrets.PRIVATE_KEY}}
        run: |
          # Add SSH key
          echo "${PRIVATE_KEY}" | sed 's/\r$//' > private_key
          chmod 600 private_key
          ssh -i private_key -o StrictHostKeyChecking=no $USER@$HOST -p $PORT << 'EOF'

          cd /var/www/TasteBud/server/ || exit

          # force reinstall nvm and node to use correct version
          export NVM_DIR="$HOME/.nvm"
          if [ ! -d "$NVM_DIR" ]; then
            echo "Installing NVM..."
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash
            source ~/.bashrc
          fi

          # Load NVM
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

          # Force install Node.js 22.11.0
          nvm install 22.11.0
          nvm use 22.11.0
          nvm alias default 22.11.0
          node -v

          # Clean untracked files (removes .env and package-lock.json)
          pm2 stop tastebud-api
          git clean -f .env 
          git pull origin main

          echo "MONGODB_URI=${{ secrets.MONGODB_URI}}" > .env
          echo "MONGO_FOODS_URI=${{secrets.EMAIL_HOST}}" >> .env
          
          
          pm2 start tastebud-api
